name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build_test: # all steps run in dev container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dev Container task
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: |
            # Add multiple commands to run if needed
            bundle install

      - name: Lint code for consistent style
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: bin/rubocop -f github

      - name: Run brakeman
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: bin/brakeman --no-pager

      - name: Run tests
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/astral-devcontainer
          cacheFrom: ghcr.io/astral-devcontainer
          push: never
          runCmd: bin/rails test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    environment: docker
    needs: [build_test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Compute repo name
        id: repo
        run: echo name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        run: |
          # Docker login to GitHub Container Registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

          # Build image
          docker pull ghcr.io/${{ steps.repo.outputs.name }}:latest || :
          docker build -f Dockerfile -t ghcr.io/${{ steps.repo.outputs.name }}:latest . \
            --cache-from ghcr.io/${{ steps.repo.outputs.name }}:latest \
            --build-arg RUBY_VERSION=${{ vars.RUBY_VERSION }} \
            --build-arg RAILS_ROOT=${{ vars.RAILS_ROOT }}

          # Push image
          docker push ghcr.io/${{ steps.repo.outputs.name }}:latest
